function execute() {
    return Response.success([
        { title: "ACTION", input: "/the-loai/action.html", script: "gen.js" },
        { title: "ADVENTURE", input: "/the-loai/adventure.html", script: "gen.js" },
        { title: "BOYS' LOVE", input: "/the-loai/boylove.html", script: "gen.js" },
        { title: "COMEDY", input: "/the-loai/comedy.html", script: "gen.js" },
        { title: "CRIME", input: "/the-loai/crime.html", script: "gen.js" },
        { title: "DRAMA", input: "/the-loai/drama.html", script: "gen.js" },
        { title: "FANTASY", input: "/the-loai/fantasy.html", script: "gen.js" },
        { title: "GIRL'S LOVE", input: "/the-loai/girllove.html", script: "gen.js" },
        { title: "HISTORICAL", input: "/the-loai/historical.html", script: "gen.js" },
        { title: "HORROR", input: "/the-loai/horror.html", script: "gen.js" },
        { title: "ISEKAI", input: "/the-loai/isekai.html", script: "gen.js" },
        { title: "MAGICAL", input: "/the-loai/magical.html", script: "gen.js" },
        { title: "MARTIAL ARTS", input: "/the-loai/martial-arts.html", script: "gen.js" },
        { title: "MECHA", input: "/the-loai/mecha.html", script: "gen.js" },
        { title: "MYSTERY", input: "/the-loai/mystery.html", script: "gen.js" },
        { title: "PHILOSOPHICAL", input: "/the-loai/philosophical.html", script: "gen.js" },
        { title: "PSYCHOLOGICAL", input: "/the-loai/psychological.html", script: "gen.js" },
        { title: "ROMANCE", input: "/the-loai/romance.html", script: "gen.js" },
        { title: "SCI-FI", input: "/the-loai/sci-fi.html", script: "gen.js" },
        { title: "SLICE OF LIFE", input: "/the-loai/slice-of-life.html", script: "gen.js" },
        { title: "SUPERHERO", input: "/the-loai/superhero.html", script: "gen.js" },
        { title: "THRILLER", input: "/the-loai/thriller.html", script: "gen.js" },
        { title: "TRAGEDY", input: "/the-loai/tragedy.html", script: "gen.js" },
    ]);
}